apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portasplit-monitor.fullname" . }}-config
  labels:
    {{- include "portasplit-monitor.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
