apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portasplit-monitor.fullname" . }}
  labels:
    {{- include "portasplit-monitor.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "portasplit-monitor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "portasplit-monitor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: portasplit-monitor
          image: {{ include "portasplit-monitor.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - -config
            - /etc/portasplit-monitor/config.yaml
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          {{- with .Values.envFromSecret.name }}
          envFrom:
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/portasplit-monitor
              readOnly: true
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "portasplit-monitor.fullname" . }}-config
        - name: tmp
          emptyDir: {}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "portasplit-monitor.fullname" . }}-data
        {{- else }}
          emptyDir: {}
        {{- end }}
